import { Technician } from "../types/TechnicianUpdated";

const techArray: Technician[] = [
  {
    _id: "1",
    name: "Albin",
    company: "IntesiveCode",
    electricalCompetence: true,
    workPermitNorway: false,
    driverLicense: true,
    specificTools: true,
    vanWithWinterTire: false,
    available: false,
    location: "Sweden",
    selected: false,
  },
  {
    _id: "2",
    name: "Amanda",
    company: "IntesiveCode",
    electricalCompetence: false,
    workPermitNorway: false,
    driverLicense: false,
    specificTools: true,
    vanWithWinterTire: true,
    available: true,
    location: "Norway",
    selected: false,
  },
  {
    _id: "3",
    name: "Leutrim",
    company: "IntesiveCode",
    electricalCompetence: true,
    workPermitNorway: false,
    driverLicense: false,
    specificTools: true,
    vanWithWinterTire: true,
    available: true,
    location: "Germany",
    selected: false,
  },
  {
    _id: "4",
    name: "Catarina",
    company: "IntesiveCode",
    electricalCompetence: true,
    workPermitNorway: false,
    driverLicense: true,
    specificTools: false,
    vanWithWinterTire: true,
    available: true,
    location: "Sweden",
    selected: false,
  },
  {
    _id: "5",
    name: "Aladin",
    company: "IntesiveCode",
    electricalCompetence: true,
    workPermitNorway: true,
    driverLicense: true,
    specificTools: false,
    vanWithWinterTire: false,
    available: true,
    location: "Norway",
    selected: false,
  },
  {
    _id: "6",
    name: "Wolcker",
    company: "IntesiveCode",
    electricalCompetence: true,
    workPermitNorway: true,
    driverLicense: true,
    specificTools: true,
    vanWithWinterTire: true,
    available: true,
    location: "Germany",
    selected: false,
  },
  {
    _id: "7",
    name: "Adam",
    company: "IntesiveCode",
    electricalCompetence: true,
    workPermitNorway: true,
    driverLicense: false,
    specificTools: false,
    vanWithWinterTire: true,
    available: true,
    location: "Denmark",
    selected: false,
  },
  {
    _id: "8",
    name: "Hesam",
    company: "IntesiveCode",
    electricalCompetence: false,
    workPermitNorway: true,
    driverLicense: true,
    specificTools: true,
    vanWithWinterTire: false,
    available: false,
    location: "Norway",
    selected: false,
  },
  {
    _id: "9",
    name: "Mohammed",
    company: "IntesiveCode",
    electricalCompetence: false,
    workPermitNorway: true,
    driverLicense: true,
    specificTools: false,
    vanWithWinterTire: false,
    available: true,
    location: "Sweden",
    selected: false,
  },
  {
    _id: "10",
    name: "Ahmed",
    company: "IntesiveCode",
    electricalCompetence: true,
    workPermitNorway: false,
    driverLicense: true,
    specificTools: true,
    vanWithWinterTire: false,
    available: false,
    location: "Poland",
    selected: false,
  },
];

export default techArray;
