import { Technician } from "../types/TechnicianUpdated";

const techArray: Technician[] = [
  {
    _id: "1",
    electricalCompetence: true,
    workPermitNorway: false,
    driverLicense: true,
    specificTools: true,
    vanWithWinterTire: false,
    available: false,
    location: "Sweden",
    selected: false,
  },
  {
    _id: "2",
    electricalCompetence: false,
    workPermitNorway: false,
    driverLicense: false,
    specificTools: true,
    vanWithWinterTire: true,
    available: true,
    location: "Norway",
    selected: false,
  },
  {
    _id: "3",
    electricalCompetence: true,
    workPermitNorway: false,
    driverLicense: false,
    specificTools: true,
    vanWithWinterTire: true,
    available: true,
    location: "Germany",
    selected: false,
  },
  {
    _id: "4",
    electricalCompetence: true,
    workPermitNorway: false,
    driverLicense: true,
    specificTools: false,
    vanWithWinterTire: true,
    available: true,
    location: "Sweden",
    selected: false,
  },
  {
    _id: "5",
    electricalCompetence: true,
    workPermitNorway: true,
    driverLicense: true,
    specificTools: false,
    vanWithWinterTire: false,
    available: true,
    location: "Norway",
    selected: false,
  },
  {
    _id: "6",
    electricalCompetence: true,
    workPermitNorway: true,
    driverLicense: true,
    specificTools: true,
    vanWithWinterTire: true,
    available: true,
    location: "Germany",
    selected: false,
  },
  {
    _id: "7",
    electricalCompetence: true,
    workPermitNorway: true,
    driverLicense: false,
    specificTools: false,
    vanWithWinterTire: true,
    available: true,
    location: "Denmark",
    selected: false,
  },
  {
    _id: "8",
    electricalCompetence: false,
    workPermitNorway: true,
    driverLicense: true,
    specificTools: true,
    vanWithWinterTire: false,
    available: false,
    location: "Norway",
    selected: false,
  },
  {
    _id: "9",
    electricalCompetence: false,
    workPermitNorway: true,
    driverLicense: true,
    specificTools: false,
    vanWithWinterTire: false,
    available: true,
    location: "Sweden",
    selected: false,
  },
  {
    _id: "10",
    electricalCompetence: true,
    workPermitNorway: false,
    driverLicense: true,
    specificTools: true,
    vanWithWinterTire: false,
    available: false,
    location: "Poland",
    selected: false,
  },
];

export default techArray;
