export enum NewWindfarmType {
  classname = "windfarm",
  title = "Add Wind Farm",
  nameSubject = "Name",
  companySubject = "Company",
  streetSubject = "Street",
  zipcodeSubject = "Zipcode",
  citySubject = "City",
  countySubject = "County",
  countrySubject = "Country",
  hubHeightSubject = "Hub Height",
  elevatorSubject = "Elevator Type",
  commissioningDateSubject = "Commissioning Date",
  safetyEquipmentSubject = "Required Safety Equipment",
  numberOfWindTurbinesSubject = "Number of Wind Turbines",
  manualSubject = "Manual",
  button = "LÄGG TILL",
}
